### ISSUE TITLE
Neue Idioms

### ISSUE THREAD

**Issue by MjPSeminar** [Mari023/Cats-Cradle#10]
Wir hätten folgenden Vorschlag: (Die jeweils erste Antwort ist die richtige.)
Idioms MajaS:

To smell a rat
1. Lunte riechen
2. Einen schlechten Geruch wahrnehmen
3. Einen Verräter in den eigenen Reihen vermuten
4. Ein gutes Geschäft wittern

To go rabbiting
1. Hasen jagen
2. Sich vermehren wie Kaninchen
3. Die Flucht ergreifen
4. Wie ein Hase hoppeln

To rat on s.o./to rat sb out
1. Jmd. Sitzenlassen, Jmd. Verpfeifen
2. Jmd. Ausbooten, Jmd. in einem Wettbewerb besiegen
3. Jmd. Beleidigen
4. Jmd. Wie eine Ratte behandeln

To do a runner
1. Die Fliege machen
2. Beim Pferderennen gewinnen
3. Einen guten Lauf haben
4. Richtig Durchstarten

A red herring
1. Eine absichtlich falsch gelegte Spur
2. Ein seltenes Exemplar von etwas
3. Anglersprache: Ein Fisch, der zu klein ist und zurückgeworfen werden muss
4. Ein auffälliges Outfit auf dem roten Teppich

Idioms Luisa:

1 See you later, Alligator 
A: sich von jemanden auf kindische Weise (für eine kurze Zeitspanne) verabschieden 
B: sich einem Krokodil verabschieden 
C: sich von einer Person verabschieden, die man für ein Krokodil hält 
D: sich darauf freuen, später ein Krokodil zu sehen 

2 Don´t look a gifted horse in the mouth
A: Einem geschenkten Pferd schaut man nicht ins Maul 
B: Das geschenkte Pferd nicht zu sehr zu betrachten 
C: Eine geschenkte Sache nicht zu hinterfragen 
D: Ein Geschenk sollte man nicht anzweifeln 

3 Early bird catches the worm 
A: Der frühe Vogel fängt den Wurm. 
B: Ein Vogel, der morgens früh aufsteht, fängt mehr. 
C: Menschen, die früh aufstehen, sind erfolgreicher an einem Tag. 
D: Um möglichst produktiv zu sein, sollte man morgens rechtzeitig aufstehen.

4 There are plenty other fish in the sea 
A: Auf der Erde gibt es genügend Menschen/Dinge, die genauso toll/gut sein können wie der oder das, was man verloren hat 
B: Es gibt genügend andere Fische im Meer 
C: Fische werden nie ausgehen im Meer 
D: Das Meer besteht nicht nur aus einer einzigen Fischart 

5 Hold your horses 
A: Mach mal langsam, immer mit der Ruhe 
B: Halte deine Pferde fest 
C: Pass auf deine Pferde auf! 
D: Unterschätze nicht die Geschwindigkeit von Pferde

**Comment by Mari023** [comment]
Ich werde mich in den nächsten Tagen darum kümmern.

**Comment by MjPSeminar** [comment]
Ich hätte noch folgenden Vorschlag: (Die jeweils erste Antwort ist wieder die richtige.)

Ram-raiding
1. Ladendiebstahl, bei dem ein gestohlenes Auto als Rammbock dient
2. Überfall auf eine Schaffarm, bei dem Widder gestohlen werden
3. Mittelalterliches Turnierelement
4. Fahrweise beim Autoscooterfahren, bei der die Anderen gerammt werden

Red in tooth and claw
1. blutrünstig, grausam
2. Von der Maul- und Klauenseuche befallen
3. Bis auf die Zähne bewaffnet
4. Eine rote Kriegsbemalung tragend

There's no room to swing a cat.
1. Es ist so eng, dass man sich kaum umdrehen kann
2. Das Kind mit dem Bade ausschütten
3. Berühmtes Zitat eines Tierschützers
4. Es gibt keinen Handlungsspielraum

To ruffle sb's/a few feathers
1. Jmd verärgern
2. Sich mit fremden Federn schmücken
3. Kein gutes Haar an jmd lassen
4. Beim Varieté : Jemandes Federboa (seine Rolle) stehlen

Running Dog
1. Ein Mitläufer
2. Ein Häftling auf der Flucht
3. Der Favorit beim Pferderennen
4. Ein Hund, der Schafe hütet

To rabbit on (about sb/sth)
1. Über etwas quasseln, schwafeln
2. Über jmd schlecht reden, lästern
3. So schnell reden wie ein Hase läuft
4. Jmd in der Luft zerreißen, ein Thema zerpflücken

Rat pack
1. Paparazzi
2. Korrupte Politiker
3. Ein Päckchen Rattengift
4. Umgangssprachlich: Verein der Kleinnagetierfreunde

Ravenhaired
1. schwarzhaarig
2. Bezeichnung des Federkleides von Raben-, Krähenvögeln
3. Als Adjektiv für eine Komödie: rabenschwarz
4. Klug wie ein Rabe

Road hog
1. Ein Verkehrsrowdy
2. Ein Igel auf der Fahrbahn
3. Jmd, der seinen Müll auf die Straße wirft
4. Hans Dampf in allen Gassen

To be in the doghouse
1. In Ungnade gefallen sein
2. In der Zwickmühle sitzen
3. Wie ein Hund hausen
4. Einen Hund als besten Freund haben

**Comment by majalorenz** [comment]
(Die erste Antwort ist jeweils die richtige)
Don’t look a gift horse in the mouth!
1. Einem geschenkten Pferd schaut man nicht ins Maul.
2. Ein Pferd zum Geburtstag geschenkt bekommen.
3. Dei Zunge rausstrecken.
4. Wenn man seinen Mund nicht aufmachen möchte.

Not to have a dog’s chance
1. Gar keine Chance haben.
2. Eine letzte Chance bekommen.
3. Seinem Hund eine Chance geben.
4. Seinem Hund keine Leckerlies geben.

To be a dead duck
1. Eine Schnapsidee.
2. Keine Chance mehr haben.
3. Komisch sein.
4. Aussehen wie eine tote Ente.

A dead bee makes no honey
1. Aus nichts wird nichts.
2. Süß wie Honig sein.
3. Es wird bald Winter.
4. Bienen produzieren Honig.

A dog’s breakfast/ dinner
1. Etwas schlecht gemacht haben.
2. Zu viel essen.
3. Nur Fleisch essen.
4. Ohne Manieren essen.

A dog’s life
1. Ein schlechtes Leben haben.
2. Ein gutes Leben haben.
3. Faul sein.
4. Zu viel Fleisch zu essen.

Every dog has his/ its day
1. Jeder hat mal einen guten Tag.
2. Jeden Tag spazieren gehen.
3. Einen schlechten Tag haben.
4. Spaß haben.

Don’t count the chicken before they are dead!
1. Du sollst den Tag nicht vor dem Abend loben!
2. Du sollst nicht alles auf einmal machen!
3. Du sollst sparsam sein!
4. Du sollst dir nicht zu viele Hühner kaufen!

The early bird catches the worm
1. Der frühe Vogel fängt den Wurm.
2. Du sollst länger schlafen.
3. Fliegt die Schwalbe hoch, wird das Wetter schöner noch.
4. Vögel essen am liebsten Würmer.

The elephant in the room
1.Ein offensichtliches Problem, was von niemandem angesprochen wird.
2. Der Elefant im Porzellanladen.
3. Dick sein.
4. Eine große Nase haben.

**Comment by Mari023** [comment]
Don´t look a gifted horse in the mouth
und 
the early bird catches the worm
haben wir jetzt doppelt, ich weder mal schauen welches von Beiden ich jetzt nehme

**Comment by MjPSeminar** [comment]
Hier noch der zweite Teil von Luisas idioms: (Die erste Antwort ist jeweils die richtige.)

To ape/apeshit
1.Ausflippen
2.Ärger mit seiner App haben
3. Mit einer App spielen
4.ein Affe werden

To back the wrong horse
1.Jemanden nutzlos unterstützen (ohne Erfolg)
2.Das falsche Pferd satteln
3.Auf dem Rücken des anderen Pferdes sitzen
4.Ein nicht passendes Pferd zurückgehen lassen

Go to the dogs!
1.Sehr schlecht gelaunt sein/in einer schlechten Stimmung sein
2.Geh zu den Hunden!
3.Jemanden etwas schlechtes wünschen
4.Zugrunde gehen

Even a worm will return
1.Selbst ein Schwächling wird es irgendwann schaffen zurückzukehren
2.Selbst ein Wurm wird wiederkommen
3.Wenn der Wurm nicht wiederkehrt, wer dann?
4.Auch ein Wurm wird umkehren

To get sb’s goat
1.Jemanden nerven
2.Die Ziege jmdn. bekommen
3.Eine Ziege von jemanden werden
4.Das Sternzeichen des Steinbockes erhalten

**Comment by CaGr123** [comment]
Ich hätte folgenden Vorschlag:
(Die erste Antwort ist jeweils die Richtige.)

in the saddle
A: in einer Machtposition
B: im Sattel sitzen
C: reiten können
D: im Sattel drin

crammed like sardines
A: eng aneinander gedrückt
B: wie die Fische im Wasser
C: so groß wie Sardinen
D: auf der Wasseroberfläche

what's sauce for the goose is sauce for the gander
A: was der eine darf, muss der andere auch dürfen
B: alle Gänse haben gleiche Möglichkeiten
C: was dem einen egal ist, ist dem anderen auch egal
D: alle Soßen schmecken gleich

to not say boo to a goose
A: schüchtern und sanft sein
B: Gänse soll man nicht erschrecken
C: mit Gänsen sprechen
D: schreckhaft sein

to behave like sheep
A: das machen, was alle machen
B: sich wie ein Schaf verhalten
C: Schafe hüten
D: mit den Schafen spielen

to seperate the sheep from the goats
A: Menschen, die etwas können, von den anderen trennen
B: Ziegen und Schafe trennen
C: die Ziegen zu den Schafen stellen
D: Kinder und Erwachsene unterscheiden

to come out of your shell
A: weniger schüchtern sein und selbstbewusst auftreten
B: die Muschel verlassen
C: das Haus verlassen
D: eine Perle in der Muschel finden

to go into your shell
A: schüchtern werden und nicht gerne mit anderen reden
B: sich in ein Haus zurückziehen
C: sich ein gutes Versteck suchen
D: in seine Heimat zurückkehren

shooting fish in a barrel
A: etwas sehr einfach finden
B: gut zielen können
C: auf Fische schießen
D: etwas sehr schwer finden

a sitting duck
A: jemand, der einfach anzugreifen ist
B: jemand, der nur rumsitzt
C: jemand, der gerne schwimmt
D: eine Ente, die nicht laufen kann

a snake in the grass
A: jemand, der freundlich tut, aber hinerhältig ist
B: jemand, der sich gut verstecken kann
C: jemand, der auf der Lauer liegt
D: jemand, der sehr klein ist

like rats leaving a sinking ship
A: wenn jemand bei Problemen die anderen im Stich lässt und verschwindet
B: wenn jemand gezwungen ist ins Wasser zu springen
C: wenn jemand versucht Ratten zu verscheuchen
D: schnell wegrennen wie eine Ratte

**Comment by MarenDormeyer** [comment]
(Die erste Antwort ist immer die richtige.)

water off a duck's back
1. jemanden völlig kalt lassen
2. wasserfest sein
3. unbeirrbar seinen Weg gehen
4. unempfänglich für gute Ratschläge sein

have a whale of a time
1. sich großartig amüsieren
2. sehr viel Zeit haben
3. eine Seereise machen
4. ein langes Leben haben

come within a whisker of sth
1. etwas stößt einem beinahe zu
2. beinahe etwas berühren
3. bei einem Wettbewerb den zweiten Platz erreichen
4. etwas ahnen

talk turkey
1. offen und unverblümt reden
2. in einer unverständlichen Sprache reden
3. undeutlich reden
4. um den heißen Brei herumreden

keep the wolf from the door
1. sich gerade so über Wasser halten
2. in Sicherheit leben
3. nicht auf Betrüger hereinfallen
4. als Einsiedler leben

a wolf in sheep's clothing
1. jemand, der einen schlechten Charakter hinter einem angenehmen Äußeren verbirgt
2. jemand, der sich unangemessen kleidet
3. ein übertrieben bescheidener Mensch
4. jemand, der unter einem Künstlernamen auftritt

like waving a red flag in front of a bull
1. jemanden absichtlich provozieren
2. sich leichtsinnig oder tollkühn verhalten
3. einer Gefahr ins Auge sehen
4. einen offensichtlichen Fehler machen

till the cow comes home
1. bis zum Abwinken
2. bevor es zu spät ist
3. bevor es Abend wird
4. solange man unbeobachtet ist

to get one's ducks in a row
1. sich gut organisiert haben
2. Macht auf andere ausüben
3. übertrieben ordentlich oder detailversessen sein
4. seinen Besitz in Sicherheit bringen

It's raining cats and dogs.
1. Es regnet sehr stark.
2. Viele verschiedene Dinge passieren gleichzeitig.
3. Es hagelt.
4. Man bekommt unerwarteten Reichtum.

**Comment by marieieiei** [comment]
Idioms Marie

To have a frog in your throat

1. Nicht mehr sprechen können/einen Frosch im Hals haben
2. Grün wie ein Frosch sein
3. Auf einmal anfangen zu quaken
4. Erkältet sein

As cute as a bugs ear

1. Sehr niedlich
2. Einen Käfer finden
3. Die Ohren offen haben
4. Tomaten auf den Ohren haben

To follow the herd

1. Der Menge hinterherlaufen
2. Dem Herd folgen
3. Jemanden verfolgen
4. Eine Pferdeherde sehen

The cat's Pyjamas

1. Der Allergrößte
2. Eine Katze in Pyjamas
3. Katzenfell
4. Pyjama mit Katzenmuster

Paper tiger

1. Person, die machtvoll erscheint, es aber nicht ist
2. Origami Tiger
3. Zirkustiger
4. gestreiftes Kleidungsstück

**Comment by corneliusbunk** [comment]
E->E

To get sb's goat:
1. to annoy sb
2. to steal sb's goat
3. to challenge sb
4. to calm sb

A leopard cannot change its spots:
1. a person can't change their character
2. people don't like to move
3. people don't like change
4. people don't like safaris

A lone wolf:
1. a person who prefers to be alone
2. a person who prefers to be around wolfs
3. a person who likes to be in the wild
4. a person who owes sth to sb

Night owl
1. a person who enjoys staying up late at night
2. a person who enjoys studying owls
3. a person who enjoys studying owls late at night
4. a person with big eyes

In the saddle
1. to be in a position of authority and control
2. to take part in a horse race
3. to ride a bike
4. to win a horse race

**Comment by eleni-r** [comment]
A little bird told me
1. Ein Vogel hat sich verirrt
2. Mir wurde etwas gesagt aber ich will nicht sagen von wem
3. Mir istv etwas passiert aber ich will nicht verraten was.
4. Jemandem ist etwas passiert aber ich sage nicht wem oder was.
Penguin suit
1. Pinguin-Kleidung
2. Pinguinversammlung
3. Frack
4. Anzug

To be blind as a bat
1. Einen guten Geruchssinn haben
2. Blind sein
3. Nachtaktiv sein
4.In der Dunkelheit nichts sehen können

to have a whale of a time
1. Die Zeit zieht sich
2. Einen Freund fürs Leben haben. 
3. Einen Wal besitzen
4. Sich amüsieren, eine tolle Zeit haben

Bear hug
1. eine herzliche warme Umarmung
2. Einen Bären umarmen
3. Bärenhöhle
4. Honigtopf

Pig headed
1. seine Meinung nicht ändern wollen
2. einen großen Kopf haben
3. Ein Schweinekopf
4. Protzig

A lone wolf
1. Jemand, der es bevorzugt alleine zu sein.
2. Eine Reihe Wölfe
3. Ein einsamer Löwe
4. Eine Einzelperson

The cat`s pyjamas
1. Katzenschlafanzug
2. Etwas exzellentes
3. Eine schlafende Katze
4. Ein müdes Kleinkind

In the dog`s house
1. Saustall
2. Dreckiges Zimmer
3. Es gibt Ärger
4. Ein Komplott wird geplant

To have a frog in your throat
1. Einen Frosch im Hals haben
2. Sich verschluckt haben
3. Sich räuspern müssen
4. einen Frosch küssen

**Comment by MiaSet** [comment]
it is a dog´s life
a ein miserables Leben führen (korrekt)
b ein glückliches Leben haben
c sich wie ein Hund fühlen
d wie ein Hund leben

till the cow comes home
a bis die Kuh nach Hause kommt
b bis zum abwinken (korrekt)
c eine lange Zeit zu Hause warten
d Kühe melken

to kill two birds with one stone
a zwei Vögel mit einem Stein töten
b Steinweitwurf
c Vogeljagd
d zwei Fliegen mit einer Klappe schlagen (korrekt)

It’s the last straw that breaks the camel’s back
a Kamele mit Stroh füttern
b Es ist der letzte Strohhalm, der dem Kamel den Rücken bricht
c Der Tropfen, der das Fass zum überlaufen bringt (korrekt)
d die Nadel im Heuhaufen suchen

Hold your horses
a seine Pferde halten
b Mach langsam, immer mit der Ruhe (korrekt)
c schnell, hastig
d reiten

**Comment by Mari023** [comment]
Filip -> #13 
JJulian -> #11

**Comment by MiaSet** [comment]
rat race:
a ständiger Konkurrenzkampf (korrekt)
b Rattenrennen
c immer auf dem Sprung sein
d ein verlorener Kampf

to be as quiet as a mouse
a mucksmäuschen still sein (korrekt)
b so klein wie eine Maus sein
c eine große Klappe haben
d im Hintergrund die Fäden ziehen

bear market
a ein Aktienmarkt, der unvorhersehbar ist (korrekt)
b ein Bärenmarkt
c der Wochenmarkt
d eine Aktiengesellschaft

to feather your own nest
a Vögel großziehen
b Geld für sich selbst ausgeben, obwohl es für etwas anderes bestimmt war (korrekt)
c großzügig sein
d Frühjahresputz

flea pit
a Flohgrube
b ein altes und dreckiges Theater oder Kino (korrekt)
c ein sauberer und schöner Ort
d ein kleines Loch
